name: 'AOP-test-MU-comp-action-windows'
on: # rebuild any PRs and main branch changes
  workflow_dispatch:

jobs:
  build: # make sure build/ci work properly
    runs-on: windows-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v3
       - name: Comp Action
         uses: aop-sanity-test/mu-test-composite-action-without-docker@v1
