name: 'AOP-MU-ORG-PERM-Test'
on:
  workflow_dispatch:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v3
       - name: Docker Action
         uses: ghec-test-org/mu-org-perm-public@0.0.1
