name: 'AOP-test-MU-docker-action-ubuntu'
on: # rebuild any PRs and main branch changes
  workflow_dispatch:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v3
       - name: Docker Action
         uses: aop-sanity-test/docker-action-public-mu@v2
