name: 'AOP-test-MU-ts-action-ubuntu'
on: # rebuild any PRs and main branch changes
  workflow_dispatch:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v3
       - name: TS Action
         uses: aop-sanity-test/mu-test-ts-action@v1
         with:
            milliseconds: 1000
