name: 'AOP-test-TS-action'
on: # rebuild any PRs and main branch changes
  workflow_dispatch:
  workflow_call:

jobs:
  reusable_workflow_job:
    uses: actions-on-packages/hello-world-go-action/.github/workflows/use_ts_action.yml@main
  build: # make sure build/ci work properly
    runs-on: macos-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v3
       - name: Ts Action
         uses: actions-on-packages/typescript-action@v1
         with:
              milliseconds : 1000
